//! Attack lookups: leaper and line tables built at compile time (const eval),
//! slider tables generated by `build.rs`.

use crate::{
    bitboard::Bitboard,
    rays,
    types::{Color, Square},
};

// Tables are laid out for PEXT only if build.rs saw BMI2; flags that reach only
// the final rustc call (`cargo rustc -- -C target-feature=...`) could disagree.
#[cfg(all(movegen_pext, not(all(target_arch = "x86_64", target_feature = "bmi2"))))]
compile_error!("slider tables were generated for PEXT but this compilation lacks BMI2; use consistent RUSTFLAGS");

/// Per-square slider lookup parameters. `magic`/`shift` are unused with PEXT.
#[cfg_attr(movegen_pext, allow(dead_code))]
pub(crate) struct Magic {
    mask: u64,
    magic: u64,
    shift: u32,
    offset: u32,
}

include!(concat!(env!("OUT_DIR"), "/slider_tables.rs"));

#[repr(C, align(64))]
struct Aligned<T>(T);

/// Target-endian u64 attack sets: 64 rook blocks, then 64 bishop blocks.
static SLIDER_ATTACKS: Aligned<[u8; SLIDER_TABLE_LEN * 8]> =
    Aligned(*include_bytes!(concat!(env!("OUT_DIR"), "/slider_attacks.bin")));

#[inline(always)]
fn slider_attacks(m: &Magic, occ: Bitboard) -> Bitboard {
    #[cfg(movegen_pext)]
    // SAFETY: `movegen_pext` implies BMI2 is enabled for this compilation (compile_error above).
    let index = unsafe { core::arch::x86_64::_pext_u64(occ.0, m.mask) } as usize;
    #[cfg(not(movegen_pext))]
    let index = ((occ.0 & m.mask).wrapping_mul(m.magic) >> m.shift) as usize;
    let table = SLIDER_ATTACKS.0.as_ptr().cast::<u64>();
    // SAFETY: build.rs reserves 2^popcount(mask) entries at `offset`; both the
    // PEXT result and the magic index (shift = 64 - popcount) are below that,
    // so the read stays inside the buffer. The buffer is 64-byte aligned and
    // holds target-endian u64 values, so the read is aligned and initialized.
    Bitboard(unsafe { table.add(m.offset as usize + index).read() })
}

#[inline(always)]
pub fn rook_attacks(sq: Square, occ: Bitboard) -> Bitboard {
    slider_attacks(&ROOK_MAGICS[sq.index()], occ)
}

#[inline(always)]
pub fn bishop_attacks(sq: Square, occ: Bitboard) -> Bitboard {
    slider_attacks(&BISHOP_MAGICS[sq.index()], occ)
}

#[inline(always)]
pub fn queen_attacks(sq: Square, occ: Bitboard) -> Bitboard {
    rook_attacks(sq, occ) | bishop_attacks(sq, occ)
}

#[inline(always)]
pub fn knight_attacks(sq: Square) -> Bitboard {
    KNIGHT[sq.index()]
}

#[inline(always)]
pub fn king_attacks(sq: Square) -> Bitboard {
    KING[sq.index()]
}

/// Squares a pawn of `color` on `sq` attacks.
#[inline(always)]
pub fn pawn_attacks(color: Color, sq: Square) -> Bitboard {
    PAWN[color.index()][sq.index()]
}

/// Squares strictly between `a` and `b` if they share a rank, file or diagonal; else empty.
#[inline(always)]
pub fn between(a: Square, b: Square) -> Bitboard {
    BETWEEN[a.index()][b.index()]
}

/// Whole board line through `a` and `b` (both included) if aligned; else empty.
#[inline(always)]
pub fn line(a: Square, b: Square) -> Bitboard {
    LINE[a.index()][b.index()]
}

static KNIGHT: [Bitboard; 64] =
    leaper_table(&[(1, 2), (2, 1), (2, -1), (1, -2), (-1, -2), (-2, -1), (-2, 1), (-1, 2)]);
static KING: [Bitboard; 64] =
    leaper_table(&[(1, 0), (1, 1), (0, 1), (-1, 1), (-1, 0), (-1, -1), (0, -1), (1, -1)]);
static PAWN: [[Bitboard; 64]; 2] = [leaper_table(&[(-1, 1), (1, 1)]), leaper_table(&[(-1, -1), (1, -1)])];
static BETWEEN: [[Bitboard; 64]; 64] = square_pairs(false);
static LINE: [[Bitboard; 64]; 64] = square_pairs(true);

const fn leaper_table(deltas: &[(i8, i8)]) -> [Bitboard; 64] {
    let mut table = [Bitboard::EMPTY; 64];
    let mut sq = 0;
    while sq < 64 {
        let mut bb = 0u64;
        let mut i = 0;
        while i < deltas.len() {
            let file = (sq % 8) as i8 + deltas[i].0;
            let rank = (sq / 8) as i8 + deltas[i].1;
            if file >= 0 && file < 8 && rank >= 0 && rank < 8 {
                bb |= 1u64 << (rank * 8 + file);
            }
            i += 1;
        }
        table[sq] = Bitboard(bb);
        sq += 1;
    }
    table
}

const fn square_pairs(full_line: bool) -> [[Bitboard; 64]; 64] {
    let mut table = [[Bitboard::EMPTY; 64]; 64];
    let mut a = 0;
    while a < 64 {
        let mut b = 0;
        while b < 64 {
            let (a_bit, b_bit) = (1u64 << a, 1u64 << b);
            let (sa, sb) = (a as u8, b as u8);
            let dirs = if rays::ray_attacks(sa, 0, &rays::ROOK_DIRS) & b_bit != 0 {
                Some(&rays::ROOK_DIRS)
            } else if rays::ray_attacks(sa, 0, &rays::BISHOP_DIRS) & b_bit != 0 {
                Some(&rays::BISHOP_DIRS)
            } else {
                None
            };
            if let Some(dirs) = dirs {
                table[a][b] = Bitboard(if full_line {
                    (rays::ray_attacks(sa, 0, dirs) & rays::ray_attacks(sb, 0, dirs)) | a_bit | b_bit
                } else {
                    rays::ray_attacks(sa, b_bit, dirs) & rays::ray_attacks(sb, a_bit, dirs)
                });
            }
            b += 1;
        }
        a += 1;
    }
    table
}
