//! Bitboard chess core: legal move generation, copy-make positions, Zobrist
//! hashing, FEN, perft.
//!
//! Slider attacks use PEXT when the build enables BMI2 on x86_64 and fancy
//! magic bitboards otherwise; both tables are generated by `build.rs`.

mod attacks;
mod bitboard;
mod board;
mod fen;
mod movegen;
mod moves;
mod perft;
mod rays;
mod types;
mod zobrist;

pub use attacks::{
    between, bishop_attacks, king_attacks, knight_attacks, line, pawn_attacks, queen_attacks, rook_attacks,
};
pub use bitboard::Bitboard;
pub use board::{Board, CastleRights};
pub use fen::{FenError, START_FEN};
pub use moves::{Move, MoveList};
pub use perft::{perft, perft_divide};
pub use types::{Color, Piece, PieceType, Square};
